Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -37,6 +37,12 @@ jobs:
       run: |
         python -m pytest test_app.py -v
 
+    - name: Debug env file
+      run: |
+        ls -la
+        echo "------ .env contents ------"
+        cat .env || echo ".env not found!"
+
   # Проверка качества кода
   lint:
     name: Code Quality Check
